version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

  # Aplicação NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://nestuser:nestpassword@postgres:5432/nestdb
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - nest-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge
